services:

  postgres-stock:
    image: postgres:15
    container_name: postgres-flowstore-stock
    environment:
      POSTGRES_DB: stockdb
      POSTGRES_USER: santt4na
      POSTGRES_PASSWORD: santt4na
    ports:
      - "5435:5432"
    volumes:
      - stock_data:/var/lib/postgresql/data
    networks:
      - flowstore-network

volumes:
  stock_data:

networks:
  flowstore-network: