services:

  postgres-notification:
    image: postgres:15
    container_name: postgres-flowstore-notification
    environment:
      POSTGRES_DB: notificationdb
      POSTGRES_USER: santt4na
      POSTGRES_PASSWORD: santt4na
    ports:
      - "5438:5432"
    volumes:
      - notification_data:/var/lib/postgresql/data
    networks:
      - flowstore-network

volumes:
  notification_data:

networks:
  flowstore-network: