services:

  postgres-order:
    image: postgres:15
    container_name: postgres-flowstore-order
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: santt4na
      POSTGRES_PASSWORD: santt4na
    ports:
      - "5434:5432"
    volumes:
      - order_data:/var/lib/postgresql/data
    networks:
      - flowstore-network

volumes:
  order_data:

networks:
  flowstore-network: