services:

  postgres-auth:
    image: postgres:15
    container_name: postgres-flowstore-auth
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: santt4na
      POSTGRES_PASSWORD: santt4na
    ports:
      - "5432:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data
    networks:
      - primestore-network

volumes:
  auth_data:

networks:
  primestore-network:
