services:

  postgres-catalog:
    image: postgres:15
    container_name: postgres-flowstore-catalog
    environment:
      POSTGRES_DB: catalogdb
      POSTGRES_USER: santt4na
      POSTGRES_PASSWORD: santt4na
    ports:
      - "5433:5432"
    volumes:
      - catalog_data:/var/lib/postgresql/data
    networks:
      - flowstore-network

volumes:
  catalog_data:

networks:
  flowstore-network: